name: test

on: 
  push: 
    branches:
      - main
  
jobs:
  run-tests:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun install
      - run: bun run test
